version: '2'

services:
  master:
    build: .
    container_name: master
    ports:
        - "3306:3306"
        - "4444:4444"
        - "4567:4567"
        - "4568:4568"
    command: mysqld --wsrep-new-cluster
    restart: always
    

  slave:
    build: .
    container_name: slave
    ports:
        - "3306:3306"
        - "4444:4444"
        - "4567:4567"
        - "4568:4568"
    command: mysqld --wsrep_cluster_address=gcomm://10.2.2.121
    restart: always
